### ISSUE TITLE
SwitchBot Token

### ISSUE THREAD

**Issue by matclothier** [OpenWonderLabs/homebridge-switchbot-openapi#11]
Hi,

There isn’t an option to generate a token in the latest version of the app on iOS. I have a hub mini and Curtains. 

Thanks,

Mat

**Comment by donavanbecker** [comment]
@matclothier, see [SwitchBotAPI](https://github.com/OpenWonderLabs/SwitchBotAPI/issues/1)

**Comment by matclothier** [comment]
Great thanks. I have requested the token. Do you know if the plug-in will support the hub mini and Curtains?

**Comment by donavanbecker** [comment]
@matclothier Since the api documents just came out a few days ago, and I just put this plugin together, no devices are working currently. 

I am planning on adding the hub mini, once I get one and once I get my token to make sure the plugin works. This is all put together thinking it will work once I get my token, but no promises. 😀 

I could potentially add curtain support in the future. There are a few other SwitchBot plugins that support the curtain but not the hub.

**Comment by matclothier** [comment]
I have 3x Curtains in pairs, a hub mini and a switch bot. I am happy to give you access to test anything you need or do testing myself. I have requested my token

**Comment by Bgoshua** [comment]
Willing to help where I can as well. Still waiting on my token, but I have a humidifier, 2 curtains (rod) and 3 switch-bots 🙌

**Comment by donavanbecker** [comment]
@Bgoshua Currently the humidifier should be working with the beta (planned release 12/25), if you wanna try it out. Sounds like they will be releasing the an app update to get the tokens around the 1st of the year.

**Comment by Bgoshua** [comment]
Rad! Thanks for the heads up!

**Comment by donavanbecker** [comment]
I will be adding support for others.

**Comment by DJay-X** [comment]
Received my Token from SwitchBot Support today and going to check things out now.

**Comment by donavanbecker** [comment]
I will be closing this issues since latest version of the SwitchBot app has been released, I will be updating the readme with instructions on how to get token.
