### ISSUE TITLE
Add Contact and Motion Sensor Support

### ISSUE THREAD

**Issue by donavanbecker** [OpenWonderLabs/homebridge-switchbot-openapi#225]
Is your feature request related to a problem? Please describe.

be able to get notifications from contact and motion sensor in the Home App.

Describe the solution you'd like

Add contact and motion sensor into Home App as their own accessories.

Describe alternatives you've considered

Additional context

**Comment by TristanBrotherton** [comment]
Another vote for this addition. I'd love to get my contact sensors into homebridge - Thank you for all your hard work.

**Comment by donavanbecker** [comment]
@TristanBrotherton once the api supports it then I will merge the pending pull request and we will be able too.

**Comment by TristanBrotherton** [comment]
You guys rock. Thank you

**Comment by DJay-X** [comment]
I guess no news on the API Side regarding contact and motion sensor? @donavanbecker @SwitchBot-Wonderlabs

**Comment by DJay-X** [comment]
Hmm.. Unfortunately, as weeks and months have passed, it seems that SwitchBot @SwitchBot-Wonderlabs @donavanbecker is no longer interested in extending the API so that the Homebridge plugin can also use the new sensors. 
Of course, it is a pity that a not inconsiderable part of the community is neglected and not heard at this point.

Due to the ongoing standstill, I cannot currently recommend the new SwitchBot hardware, at least to Homebridge and HomeKit enthusiasts. Not much has remained of the original enthusiasm and commitment with regard to the API and Homebridge. 

I hope this will change in the near future and we will be happy to report about SwitchBot again on SmartApfel.de

**Comment by donavanbecker** [comment]
@DJay-X https://github.com/OpenWonderLabs/python-host/wiki

Here is the connection through BLE, which I would want to implement into the new @switchbot/homebridge-switchbot plugin so that both BLE and OpenAPI are in the same plugin, but I have had time and really don't know how to implement this on node-switchbot

**Comment by DJay-X** [comment]
@donavanbecker Thanks. According to a latest statement from the developers, the API for sensors is now available.
Looking forward to hear from you with an update of the plugin. Can't wait. Thanks a lot for your time and effort giving this to the community. 👍

**Comment by donavanbecker** [comment]
@DJay-X, hopefully I get time in a few days. Would you like to beta test?

**Comment by DJay-X** [comment]
Thanks. I'll give it a try in the next days switching to the new Plugin. And of course I can Beta test with the Contact- and Motion sensor. :)

**Comment by donavanbecker** [comment]
@DJay-X I have release v0.1.0 of @switchbot/homebridge-switchbot plugin that supports the contact sensors, motion sensors, and water level for humidifiers.
