### ISSUE TITLE
SwitchBot bot choice of device 

### ISSUE THREAD

**Issue by djjlipod** [OpenWonderLabs/homebridge-switchbot-openapi#75]
**Is your feature request related to a problem? Please describe.**

a great feature would be to change how the SwitchBot bot shows in HomeKit, such as a tv or a speaker or a coffee machine. it would be great for setting routines

**Describe the solution you'd like**

<!-somewhere in the api settings allow to choose from a list of what the SwitchBotJapan will show in home as -->

**Describe alternatives you've considered**

<!-n/a. -->

**Additional context**

**Comment by donavanbecker** [comment]
@djjlipod, with there being so many different devices that you could set a bot too, I feel like the best option is outlet, since it can be set as a light, outlet, or fan. I could add the option of setting it as a switch also.... 

If anyone submits a PR for it to be something like a TV, I would consider merging.
